---

_You are currently looking at **version 1.2** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

# Assignment 2 - Pandas Introduction
All questions are weighted the same in this assignment.
## Part 1
The following code loads the olympics dataset (olympics.csv), which was derrived from the Wikipedia entry on [All Time Olympic Games Medals](https://en.wikipedia.org/wiki/All-time_Olympic_Games_medal_table), and does some basic data cleaning. 

The columns are organized as # of Summer games, Summer medals, # of Winter games, Winter medals, total # number of games, total # of medals. Use this dataset to answer the questions below.

In [1]:
import pandas as pd

df = pd.read_csv('olympics.csv', index_col=0, skiprows=1)

for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold'+col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver'+col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze'+col[4:]}, inplace=True)
    if col[:1]=='№':
        df.rename(columns={col:'#'+col[1:]}, inplace=True)

names_ids = df.index.str.split('\s\(') # split the index by '('

df.index = names_ids.str[0] # the [0] element is the country name (new index) 
df['ID'] = names_ids.str[1].str[:3] # the [1] element is the abbreviation or ID (take first 3 characters from that)

df = df.drop('Totals')
df.head()

# Summer  Gold  Silver  Bronze  Total  # Winter  Gold.1  \
Afghanistan        13     0       0       2      2         0       0   
Algeria            12     5       2       8     15         3       0   
Argentina          23    18      24      28     70        18       0   
Armenia             5     1       2       9     12         6       0   
Australasia         2     3       4       5     12         0       0   

             Silver.1  Bronze.1  Total.1  # Games  Gold.2  Silver.2  Bronze.2  \
Afghanistan         0         0        0       13       0         0         2   
Algeria             0         0        0       15       5         2         8   
Argentina           0         0        0       41      18        24        28   
Armenia             0         0        0       11       1         2         9   
Australasia         0         0        0        2       3         4         5   

             Combined total   ID  
Afghanistan               2  AFG  
Algeria                  15  ALG  
Argentina                70  ARG  
Armenia                  12  ARM  
Australasia              12  ANZ

### Question 0 (Example)

What is the first country in df?

*This function should return a Series.*

In [8]:
# You should write your whole answer within the function provided. The autograder will call
# this function and compare the return value against the correct solution value
def answer_zero():
    # This function returns the row for Afghanistan, which is a Series object. The assignment
    # question description will tell you the general format the autograder is expecting
    return df.iloc[0]

# You can examine what your function returns by calling it in the cell. If you have questions
# about the assignment formats, check out the discussion forums for any FAQs
answer_zero() 


# Summer           13
Gold                0
Silver              0
Bronze              2
Total               2
# Winter            0
Gold.1              0
Silver.1            0
Bronze.1            0
Total.1             0
# Games            13
Gold.2              0
Silver.2            0
Bronze.2            2
Combined total      2
ID                AFG
Name: Afghanistan, dtype: object

### Question 1
Which country has won the most gold medals in summer games?

*This function should return a single string value.*

In [16]:
def answer_one():
    rt = df.copy()
    
    v = rt['Gold.2'].idxmax()
    print(v)

answer_one()

United States


In [10]:
answer_one()

'United States'

### Question 2
Which country had the biggest difference between their summer and winter gold medal counts?

*This function should return a single string value.*

In [11]:
def answer_two():
    r = df.copy()
    r["result"] = (r["Gold"]-r["Gold.1"])
    s=r[r["result"]==max(r["result"])].index[0]
    return s

In [12]:
answer_two()


'United States'

### Question 3
Which country has the biggest difference between their summer gold medal counts and winter gold medal counts relative to their total gold medal count? 

$$\frac{Summer~Gold - Winter~Gold}{Total~Gold}$$

Only include countries that have won at least 1 gold in both summer and winter.

*This function should return a single string value.*

In [48]:
# def answer_three():
#     q = df.copy()
#     r=q.where(q["Gold"]>1)
#     r=q.where(q["Gold.1"]>1)
#     r["result"] = (r["Gold"]-r["Gold.1"])
#     r["result1"]=r["result"]/(r["Gold"]+r["Gold.1"])
#     s=r[r["result1"]==max(r["result1"])].index[0]
#     return s
# answer_three()

q=df.copy()
q =q.where(df['Gold']>1)
q =q.where(df['Gold.1']>1)
q=q.dropna()
q['res']=q['Gold']-q['Gold.1']
q

# Summer   Gold  Silver  Bronze   Total  # Winter  \
Australia                   25.0  139.0   152.0   177.0   468.0      18.0   
Austria                     26.0   18.0    33.0    35.0    86.0      22.0   
Belarus                      5.0   12.0    24.0    39.0    75.0       6.0   
Canada                      25.0   59.0    99.0   121.0   279.0      22.0   
China                        9.0  201.0   146.0   126.0   473.0      10.0   
Croatia                      6.0    6.0     7.0    10.0    23.0       7.0   
Czech Republic               5.0   14.0    15.0    15.0    44.0       6.0   
Czechoslovakia              16.0   49.0    49.0    45.0   143.0      16.0   
Estonia                     11.0    9.0     9.0    15.0    33.0       9.0   
Finland                     24.0  101.0    84.0   117.0   302.0      22.0   
France                      27.0  202.0   223.0   246.0   671.0      22.0   
Germany                     15.0  174.0   182.0   217.0   573.0      11.0   
United Team of Germany       3.0   28.0    54.0    36.0   118.0       3.0   
East Germany                 5.0  153.0   129.0   127.0   409.0       6.0   
West Germany                 5.0   56.0    67.0    81.0   204.0       6.0   
Great Britain               27.0  236.0   272.0   272.0   780.0      22.0   
Italy                       26.0  198.0   166.0   185.0   549.0      22.0   
Japan                       21.0  130.0   126.0   142.0   398.0      20.0   
South Korea                 16.0   81.0    82.0    80.0   243.0      17.0   
Netherlands                 25.0   77.0    85.0   104.0   266.0      20.0   
Norway                      24.0   56.0    49.0    43.0   148.0      22.0   
Poland                      20.0   64.0    82.0   125.0   271.0      22.0   
Russia                       5.0  132.0   121.0   142.0   395.0       6.0   
Soviet Union                 9.0  395.0   319.0   296.0  1010.0       9.0   
Unified Team                 1.0   45.0    38.0    29.0   112.0       1.0   
Slovakia                     5.0    7.0     9.0     8.0    24.0       6.0   
Slovenia                     6.0    4.0     6.0     9.0    19.0       7.0   
Sweden                      26.0  143.0   164.0   176.0   483.0      22.0   
Switzerland                 27.0   47.0    73.0    65.0   185.0      22.0   
Ukraine                      5.0   33.0    27.0    55.0   115.0       6.0   
United States               26.0  976.0   757.0   666.0  2399.0      22.0   

                        Gold.1  Silver.1  Bronze.1  Total.1  # Games  Gold.2  \
Australia                  5.0       3.0       4.0     12.0     43.0   144.0   
Austria                   59.0      78.0      81.0    218.0     48.0    77.0   
Belarus                    6.0       4.0       5.0     15.0     11.0    18.0   
Canada                    62.0      56.0      52.0    170.0     47.0   121.0   
China                     12.0      22.0      19.0     53.0     19.0   213.0   
Croatia                    4.0       6.0       1.0     11.0     13.0    10.0   
Czech Republic             7.0       9.0       8.0     24.0     11.0    21.0   
Czechoslovakia             2.0       8.0      15.0     25.0     32.0    51.0   
Estonia                    4.0       2.0       1.0      7.0     20.0    13.0   
Finland                   42.0      62.0      57.0    161.0     46.0   143.0   
France                    31.0      31.0      47.0    109.0     49.0   233.0   
Germany                   78.0      78.0      53.0    209.0     26.0   252.0   
United Team of Germany     8.0       6.0       5.0     19.0      6.0    36.0   
East Germany              39.0      36.0      35.0    110.0     11.0   192.0   
West Germany              11.0      15.0      13.0     39.0     11.0    67.0   
Great Britain             10.0       4.0      12.0     26.0     49.0   246.0   
Italy                     37.0      34.0      43.0    114.0     48.0   235.0   
Japan                     10.0      17.0      18.0     45.0     41.0   140.0   
South Korea               26.0      17.

### Question 4
Write a function that creates a Series called "Points" which is a weighted value where each gold medal (`Gold.2`) counts for 3 points, silver medals (`Silver.2`) for 2 points, and bronze medals (`Bronze.2`) for 1 point. The function should return only the column (a Series object) which you created, with the country names as indices.

*This function should return a Series named `Points` of length 146*

In [14]:
def answer_four():
    rt = df.copy()
    rt['Points']=(rt["Gold.2"]*3) + (rt["Silver.2"]*2) + (rt['Bronze.2']* 1)
    Points = rt["Points"]
    return Points
answer_four()

Afghanistan                           2
Algeria                              27
Argentina                           130
Armenia                              16
Australasia                          22
                                   ... 
Yugoslavia                          171
Independent Olympic Participants      4
Zambia                                3
Zimbabwe                             18
Mixed team                           38
Name: Points, Length: 146, dtype: int64

## Part 2
For the next set of questions, we will be using census data from the [United States Census Bureau](http://www.census.gov). Counties are political and geographic subdivisions of states in the United States. This dataset contains population data for counties and states in the US from 2010 to 2015. [See this document](https://www2.census.gov/programs-surveys/popest/technical-documentation/file-layouts/2010-2015/co-est2015-alldata.pdf) for a description of the variable names.

The census dataset (census.csv) should be loaded as census_df. Answer questions using this as appropriate.

### Question 5
Which state has the most counties in it? (hint: consider the sumlevel key carefully! You'll need this for future questions too...)

*This function should return a single string value.*

In [15]:
census_df = pd.read_csv('census.csv')
census_df[:20]

SUMLEV  REGION  DIVISION  STATE  COUNTY   STNAME          CTYNAME  \
0       40       3         6      1       0  Alabama          Alabama   
1       50       3         6      1       1  Alabama   Autauga County   
2       50       3         6      1       3  Alabama   Baldwin County   
3       50       3         6      1       5  Alabama   Barbour County   
4       50       3         6      1       7  Alabama      Bibb County   
5       50       3         6      1       9  Alabama    Blount County   
6       50       3         6      1      11  Alabama   Bullock County   
7       50       3         6      1      13  Alabama    Butler County   
8       50       3         6      1      15  Alabama   Calhoun County   
9       50       3         6      1      17  Alabama  Chambers County   
10      50       3         6      1      19  Alabama  Cherokee County   
11      50       3         6      1      21  Alabama   Chilton County   
12      50       3         6      1      23  Alabama   Choctaw County   
13      50       3         6      1      25  Alabama    Clarke County   
14      50       3         6      1      27  Alabama      Clay County   
15      50       3         6      1      29  Alabama  Cleburne County   
16      50       3         6      1      31  Alabama    Coffee County   
17      50       3         6      1      33  Alabama   Colbert County   
18      50       3         6      1      35  Alabama   Conecuh County   
19      50       3         6      1      37  Alabama     Coosa County   

    CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010  ...  RDOMESTICMIG2011  \
0         4779736            4780127          4785161  ...          0.002295   
1           54571              54571            54660  ...          7.242091   
2          182265             182265           183193  ...         14.832960   
3           27457              27457            27341  ...         -4.728132   
4           22915              22919            22861  ...         -5.527043   
5           57322              57322            57373  ...          1.807375   
6           10914              10915            10887  ...        -30.953709   
7           20947              20946            20944  ...        -14.032727   
8          118572             118586           118437  ...         -6.155670   
9           34215              34170            34098  ...         -2.731639   
10          25989              25986            25976  ...          6.339327   
11          43643              43631            43665  ...         -1.372935   
12          13859              13858            13841  ...        -15.455274   
13          25833              25840            25767  ...         -6.194363   
14          13932              13932            13880  ...        -10.744102   
15          14972              14972            14973  ...         -3.673524   
16          49948              49948            50177  ...          0.377640   
17          54428              54428            54514  ...         -0.073423   
18          13228              13228            13208  ...         -4.861559   
19          11539              11758            11758  ...        -33.930581   

    RDOMESTICMIG2012  RDOMESTICMIG2013  RDOMESTICMIG2014  RDOMESTICMIG2015  \
0          -0.193196          0.381066          0.582002         -0.467369   
1          -2.915927         -3.012349          2.265971         -2.530799   
2          17.647293         21.845705         19.243287         17.197872   
3          -2.500690         -7.056824         -3.904217        -10.543299   
4          -5.068871         -6.201001         -0.177537          0.177258   
5          -1.177622         -1.748766         -2.062535         -1.369970   
6          -5.180127         -1.130263         14.354290        -16.167247   
7         -11.684234         -5.655413          1.085428         -6.529805   
8          -4.611706         -5.524649         -4.463211         -3.376322   
9        

In [16]:
def answer_five():
    rt = census_df.copy()
    id_S = list(rt['STNAME'].unique())
    rt = rt.set_index('STNAME')
    r = list(rt['CTYNAME'].index)
    c = (list(map(lambda x: r.count(x),id_S)))
    m = max(c)
    result=id_S[c.index(m)]
    
    return result

answer_five()


'Texas'

### Question 6
**Only looking at the three most populous counties for each state**, what are the three most populous states (in order of highest population to lowest population)? Use `CENSUS2010POP`.

*This function should return a list of string values.*

In [96]:
# def answer_six():
#     rt = census_df.copy()
#     rt = rt[rt['SUMLEV']==50]
#     rt = rt.set_index('STNAME')
    
#     r= sorted(rt['CENSUS2010POP'])
#     r = r[-3:]
#     result = list(map(lambda x: str(rt[rt['CENSUS2010POP']==x].index[0]),r))
    
#     return result[::-1]

# answer_six()
l=[]
rt = census_df.copy()
rt = rt[rt['SUMLEV']==50]
rt = rt.set_index('STNAME')
for i in range(3):
    
    r= rt['CENSUS2010POP'].idxmax()
    l.append(r)
    rt=rt.drop([r])
l[1],l[2]=l[2],l[1]
l


['California', 'Texas', 'Illinois']

### Question 7
Which county has had the largest absolute change in population within the period 2010-2015? (Hint: population values are stored in columns POPESTIMATE2010 through POPESTIMATE2015, you need to consider all six columns.)

e.g. If County Population in the 5 year period is 100, 120, 80, 105, 100, 130, then its largest change in the period would be |130-80| = 50.

*This function should return a single string value.*

In [69]:
def answer_seven():
    
    rt = census_df.copy()
    rt = rt[rt['SUMLEV']==50]
    rt = rt.set_index('CTYNAME')
    rt = rt[['POPESTIMATE2010','POPESTIMATE2011','POPESTIMATE2012','POPESTIMATE2013','POPESTIMATE2014','POPESTIMATE2015']]
    rt_max = rt.max(axis=1)
    rt_min = rt.min(axis=1)
    rt['res']=rt_max-rt_min
    v=rt[rt['res']==max(rt['res'])].index[0]

    return v
answer_seven()

'Harris County'

### Question 8
In this datafile, the United States is broken up into four regions using the "REGION" column. 

Create a query that finds the counties that belong to regions 1 or 2, whose name starts with 'Washington', and whose POPESTIMATE2015 was greater than their POPESTIMATE 2014.

*This function should return a 5x2 DataFrame with the columns = ['STNAME', 'CTYNAME'] and the same index ID as the census_df (sorted ascending by index).*

In [127]:
def answer_eight():
    rt = census_df.copy()
    r1 = rt[rt['REGION']==1]
    rt = rt[rt['REGION']==1].append(rt[rt['REGION']==2])[rt["CTYNAME"]=="Washington County"][rt["POPESTIMATE2015"]>rt['POPESTIMATE2014']]
    rt = rt[['STNAME','CTYNAME']]
    rt = rt.sort()
    return rt
answer_eight()


STNAME            CTYNAME
896           Iowa  Washington County
1419     Minnesota  Washington County
2345  Pennsylvania  Washington County
2355  Rhode Island  Washington County
3163     Wisconsin  Washington County